In [1]:
import pandas as pd 
import numpy  as np
import matplotlib .pyplot as plt
import scipy.stats as stats
from sklearn .model_selection import train_test_split,cross_val_score
from sklearn .compose import ColumnTransformer
from sklearn .tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import seaborn as sns
from sklearn .preprocessing import KBinsDiscretizer

In [2]:
data=pd.read_csv(r"C:\Users\mdfir\Downloads\train.csv",usecols=["Age","Fare","Survived"])

In [3]:
data.head(2)

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833

In [4]:
data.dropna(inplace=True)

In [5]:
data

Survived   Age     Fare
0           0  22.0   7.2500
1           1  38.0  71.2833
2           1  26.0   7.9250
3           1  35.0  53.1000
4           0  35.0   8.0500
..        ...   ...      ...
885         0  39.0  29.1250
886         0  27.0  13.0000
887         1  19.0  30.0000
889         1  26.0  30.0000
890         0  32.0   7.7500

[714 rows x 3 columns]

In [6]:
data.shape

(714, 3)

In [7]:
x=data.iloc[:,1:]
y=data.iloc[:,0]

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=42)

In [9]:
x_train

Age      Fare
328  31.0   20.5250
73   26.0   14.4542
253  30.0   16.1000
719  33.0    7.7750
666  25.0   13.0000
..    ...       ...
92   46.0   61.1750
134  25.0   13.0000
337  41.0  134.5000
548  33.0   20.5250
130  33.0    7.8958

[571 rows x 2 columns]

In [10]:
y_train

328    1
73     0
253    0
719    0
666    0
      ..
92     0
134    0
337    1
548    0
130    0
Name: Survived, Length: 571, dtype: int64

In [11]:
t=DecisionTreeClassifier()

In [12]:
t.fit(x_train,y_train)

DecisionTreeClassifier()

In [13]:
pred=t.predict(x_test)

In [14]:
pred

array([1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1], dtype=int64)

In [15]:
score=accuracy_score(y_test,pred)

In [16]:
score

0.6223776223776224

In [17]:
csv=cross_val_score(t,x,y,cv=10,scoring="accuracy")

In [18]:
csv.mean()

0.628971048513302

# use discretized encoding 

In [55]:
kbin_age=KBinsDiscretizer(n_bins=5,encode="ordinal",strategy="uniform")
kbin_fare=KBinsDiscretizer(n_bins=5,encode="ordinal",strategy="uniform")

In [57]:
cl=ColumnTransformer([
    ("first",kbin_age,[0]),
    ("second",kbin_fare,[1])
])

In [59]:
x_train_cl=cl.fit_transform(x_train)
x_test_cl=cl.fit_transform(x_test)

# show the my bins columns 

In [51]:
cl.named_transformers_["first"].n_bins_

array([5])

In [61]:
cl.named_transformers_["first"].bin_edges_

array([array([ 1. , 13.2, 25.4, 37.6, 49.8, 62. ])], dtype=object)

In [63]:
clf=DecisionTreeClassifier()

In [65]:
clf.fit(x_train_cl,y_train)

DecisionTreeClassifier()

In [81]:
y_pred=clf.predict(x_test_cl)

In [83]:
y_pred

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [85]:
from sklearn .metrics import accuracy_score

In [91]:
score=np.mean(accuracy_score(y_test,y_pred))

In [93]:
score

0.6083916083916084